- name: Install a Rust Server
  hosts: rustserver
  connection: local
  gather_facts: True

  vars:
    default_password: "{{ 'LetsGoWithABigPassword' | password_hash('sha512', 'mysecretsalt') }}"


  tasks:
    - name: Ensure user exists
      become: yes
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: /bin/bash
        state: present
      loop: "{{ rust_instances }}"

    - name: Download and Install LGSM
      include_tasks: tasks/install-lgsm.yml
      loop: "{{ rust_instances }}"

    - name: Set up web panel
      include_tasks: tasks/setup-lgsm-web.yml
      loop: "{{ rust_instances }}"
      when: 1==0
    
