- name: Set up the LGSM web panel
  become: true
  block:

    - name: Copy web files to users home
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/files/web/"
        dest: "/home/{{ item.name }}/"
        owner: "{{ item.name }}"
        group: "{{ item.name }}"

    - name: Generate HTTP conf
      ansible.builtin.template:
        src: http.conf.j2
        dest: /etc/apache2/sites-available/{{ item.name }}.conf
      loop: "{{ rust_instances }}"
 
